### ISSUE TITLE
Tracking Habitat versioning

### ISSUE THREAD

**Issue by fifthecho** [biome-sh/biome#9]
At the time of writing, the latest version of Biome is 1.6.42 and the latest (stable) version of Habitat is 1.6.39.

Shouldn't the releases track the Habitat versioning to allow easier migration back and forth rather than potentially bringing in untested/unreliable code from Habitat?

**Comment by fifthecho** [comment]
And while I support building/testing new features, my bigger concern is around tagging the releases as stable and in the Habitat/Biome bldr environments

**Comment by jsirex** [comment]
Hello. 
My intention here is to get new changes as soon as possible, because some of them has critical fixes which I test locally. Sometimes releases are same. For example diff 39-42 is:
1.6.40 - changelog
1.6.41 - docs + minor cargo update (no code changes)
1.6.42 - ci changes.

On other hand biome sometime can make something like tech preview. I personally think, versions are not necessarily required to be same .

**Comment by jsirex** [comment]
Does it sounds acceptable? May I close the issue?
